ci: fixed the workflow and bash script for running tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,4 +33,16 @@ jobs:
           target: google_apis
           arch: x86_64
           script: |
-            ./run_tests.sh
+            # Находим ID эмулятора внутри этого блока
+            EMULATOR_ID=$(adb devices | grep emulator | cut -f1)
+            
+            # Проверяем, найден ли эмулятор
+            if [ -z "$EMULATOR_ID" ]; then
+              echo "Error: No emulator found. Exiting."
+              exit 1
+            fi
+            
+            echo "Found emulator: $EMULATOR_ID"
+            
+            # Передаем найденный ID в скрипт
+            ./run_tests.sh -d "$EMULATOR_ID"
